logging:
  level:
    com:
      eva-9: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eva9?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver