spring:
  application:
    name: Eva-9
  profiles:
    active: dev
server:
  port: 1226
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.eva9.model
# spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop
