logging:
  level:
    com:
      eva-9: INFO
spring:
  datasource:
    url: jdbc:mysql://jinwei.fun:3306/eva9?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: eva9
    password: eva9
    driver-class-name: com.mysql.jdbc.Driver